name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  # 1 second intervals between tmux screencapts:
  TMXBGDT: 1

jobs:
  tests:
    name: PDS Tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up the Mamba Cache
        uses: actions/cache@v2
        env:
          # Count up to have bootstrap test build a new mamba:
          cache_name: mamba-1
        with:
          path: ~/pds
          key: ${{ runner.os }}-build-${{ env.cache_name }}

      - name: Bootstrap
        shell: bash -l {0}
        run: "wget 'https://raw.githubusercontent.com/AXGKl/pds/master/setup/pds.sh' && chmod +x pds.sh && ./pds.sh install && rm -rf $HOME/pds/pkgs"

      - name: TMUX Tests
        shell: bash -l {0}
        run: "cd $HOME/.config/pds && test/test_tmux.sh"

      - name: Script Tests
        shell: bash -l {0}
        run: "cd $HOME/.config/pds && test/test_pds_script.sh"
