name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  # 1 second intervals between tmux screencapts:
  TMXBGDT: 1

jobs:
  tests:
    name: Tests PDS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: bootstrap
        shell: bash -l {0}
        run: "test/test_bootstrap.sh"
      - name: pds_script
        shell: bash -l {0}
        run: "test/test_pds_script.sh"
