name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  # 1 second intervals between tmux screencapts:
  TMXBGDT: 1

jobs:
  tests:
    name: Tests PDS
    runs-on: ubuntu-latest

    steps:
      - name: bootstrap
        shell: bash -l {0}
        run: "wget 'https://raw.githubusercontent.com/AXGKl/pds/master/setup/pds.sh' && chmod +x pds.sh && ./pds install"
      - name: pds_script
        shell: bash -l {0}
        run: "cd $HOME/.config/pds && test/test_pds_script.sh"
